@startuml "Guitar Shop"

class Main{
    +HandleLogin(username, password)
    +HandleSearch(guitarspec)
    +HandleUpdateGuitar(guitar, guitarspec, price)
    +HandleRemoveGuitar(guitar)
}

abstract class Instrument{
    SerialNumber
    Price
}

class GuitarSpecification{
    Builder
    BackWood
    TopWood
    Type
    Model: String
}

class PianoSpecification{
    
}
class DrumSpecification{

}

interface Repository{
    +Add(Entity)
    +AddRange(EntityList)
    +Remove(Entity)
    +findById(Id)
    +findByKey(KeySelector, Key)
    +getAll()
}

class Piano{

}

class Drum{

}

class Guitar{

}

class InstrumentController{
    +Search(InstrumentSpec)
    +Add(User, Instrument)
    +AddBulk(User, InstrumentSpec, SerialNumbers)
    +RemoveInstrumentById(User, Id)
    +RemoveInstrument(User, Instrument)
}

class InstrumentRepository{
    
}

enum Builder{
    FENDER
    MARTIN
    GIBSON
    COLLINGS
    OLSON
    RYAN
    PRS
    ANY
}

enum Wood{
    ALDER
    ADIRONDACK
    BRAZILIAN_ROSEWOOD
    CEDAR
    COCOBOLO
    INDIAN_ROSEWOOD
    MAHOGANY
    MAPLE
    SITKA
}

enum Type{
    ELECTRIC
    ACOUSTIC
}

interface Database{
    +SaveChanges()
    +LoadDatabase()
    +Set<Type>()
}

class JsonDatabase {
    +SerializeObject(Entity)
    +DeserializeObject(Entity)
}

abstract class User{
    Id
    Username
    Password
    FirstName
    LastName
}

class UserRepository{

}

class UserController{
    +SignIn(username, password)
    +SignOut()
    +ResetPassword(username, currentPassword, newPassword)
}

class Employee{

}
class Customer{

}

Guitar --> GuitarSpecification
GuitarSpecification --> Builder
GuitarSpecification --> Wood
GuitarSpecification --> Type
JsonDatabase --|> Database

Customer --|> User
Employee --|> User
UserRepository --|> Repository
UserRepository --> Database
UserController --> UserRepository
UserRepository --> "*" User
Main --> UserController
Main --> "*" InstrumentController

InstrumentRepository --|> Repository
InstrumentController --> InstrumentRepository
InstrumentRepository --> "*" Instrument
Piano --|> Instrument
Guitar --|> Instrument
Drum --|> Instrument

Piano --> PianoSpecification
Drum --> DrumSpecification

@enduml